openapi: 3.0.0
info:
  title: Nintendo Switch API
  description: API RESTful para gestionar juegos de Nintendo Switch con autenticación JWT.
  version: 1.0.0
servers:
  - url: https://nintendo-switch-api.onrender.com/api
    description: Servidor en producción (Render)
  - url: http://localhost:3000/api
    description: Servidor local
paths:
  /auth/register:
    post:
      summary: Registra un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: mario
                password:
                  type: string
                  example: 123456
              required:
                - username
                - password
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                  token:
                    type: string
        '400':
          description: Error (límite alcanzado o usuario existente)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Se ha alcanzado el límite máximo de usuarios registrados
  /auth/login:
    post:
      summary: Inicia sesión y devuelve un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: mario
                password:
                  type: string
                  example: 123456
              required:
                - username
                - password
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                  token:
                    type: string
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usuario no encontrado
  /games:
    get:
      summary: Lista todos los juegos
      responses:
        '200':
          description: Lista de juegos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
    post:
      summary: Crea un nuevo juego
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameInput'
      responses:
        '201':
          description: Juego creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Validación fallida
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        msg:
                          type: string
        '401':
          description: Token requerido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Token requerido
  /games/{id}:
    get:
      summary: Obtiene un juego por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del juego
      responses:
        '200':
          description: Juego encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: ID inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        msg:
                          type: string
        '404':
          description: Juego no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Game not found
    put:
      summary: Actualiza un juego
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del juego
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameInput'
      responses:
        '200':
          description: Juego actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Validación fallida
        '401':
          description: Token requerido
        '404':
          description: Juego no encontrado
    delete:
      summary: Elimina un juego
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del juego
      responses:
        '204':
          description: Juego eliminado
        '400':
          description: ID inválido
        '401':
          description: Token requerido
        '404':
          description: Juego no encontrado
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        genre:
          type: string
        releaseDate:
          type: string
          format: date
        publisher:
          type: string
      required:
        - id
        - title
        - releaseDate
        - publisher
    GameInput:
      type: object
      properties:
        title:
          type: string
        genre:
          type: string
        release_date:
          type: string
          format: date
        publisher:
          type: string
          enum: [Nintendo, Capcom, Square Enix, Bandai Namco]
      required:
        - title
        - release_date
        - publisher
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT